const SET_ORDER = 'SET_ORDER';
const SET_GENRE = 'SET_GENRE';
const SET_TYPE = 'SET_TYPE';
const SET_SEARCH = 'SET_SEARCH';
const SET_CONTENT = 'SET_CONTENT';

export {
  SET_ORDER, SET_GENRE, SET_TYPE, SET_SEARCH, SET_CONTENT,
};
